### ISSUE TITLE
Auth Seems not working

### ISSUE THREAD

**Issue by villa1** [SnoyIatK/3proxy#2]
although i set up for asking authentication ,but it seems proxy is able to run without providing any username password (accessible by outworld or my server become public proxy)

**Comment by malikshi** [comment]
i think auth not working under NTLM

**Comment by snoyiatk** [comment]
@villa1 You can try latest configuration file.
I've made some changes in latest commit that should fix auth problem.
It was fixed long time ago but I forgot to update it to the repo.

**Comment by snoyiatk** [comment]
Close this.
